"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*%ve0fa9*l&dq3ao8ke(j)t3dz2(@n5t)r(^w_o0f8669z9yny"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'website',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "webapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "webapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# AWS Credentials
AWS_ACCESS_KEY_ID = 'eyJraWQiOiJUb01OMzNvb05RVWlMamNxaFZsNndGRmIyVnUwMXRRMFE3WEJIVWFMMGRBPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxNDM4MTQyOC1lMDExLTcwYTgtNGE2Zi0xOTZmNWYyNjcwYjUiLCJjb2duaXRvOmdyb3VwcyI6WyJ1cy1lYXN0LTFfYzYzeExEYmhxX0dvb2dsZSJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9jNjN4TERiaHEiLCJ2ZXJzaW9uIjoyLCJjbGllbnRfaWQiOiIxbWMyZnFyNmVobzkwYWswdGFqZXV2NTVncSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhdXRoX3RpbWUiOjE3MTc1NTA0OTksImV4cCI6MTcxNzU1NDA5OSwiaWF0IjoxNzE3NTUwNTAwLCJqdGkiOiI1NjE2OTVmYi0xOTM0LTRmNDctYmJlZC1mYzM0NGZhZDk3MmYiLCJ1c2VybmFtZSI6Imdvb2dsZV8xMDcxNzg0MTE1NDkzMjIzNjA3NTUifQ.v12RlvCfGkQu50Rjq7SoqLn7d5WvaEeqQv9pOMddLtDV_BEUurKPYbqsNIol_H0yfwwH5r90rPmHZ5nP35wpX-f_y2-cYxZGWsit9F3qZhXtKulKq26yLwKbpiAztbSvH5Ds8RR92wSUS_PMEM_LrGaBS14HkApKK3jAWk5CEJatusSRWm2dYbQfdmVEei9VSP5M2k8RdrfwKcykLQ6Kk1JHjXsGBhmcW8Ko0Cj1sEaj8XgMCc-GI5nxJP-uTmN9Xa73ZQEse_7s6uHBNUFP3qjNB5GGQVrq61R0ggjlzmTGk5tvsjGdU7QKp0qAWTVGcmAcUSOyi4utBPG-Cn_Vbw'
AWS_SECRET_ACCESS_KEY = 'eyJraWQiOiJhVVNWbGFtUFdsaHFDbFZ4SGNXQnBpZndZV2c5NzJsVjJjOFJmRXBDTGpNPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiUGNNcDJ2ZHYxRkZvUjdwUDFIMklGdyIsInN1YiI6IjE0MzgxNDI4LWUwMTEtNzBhOC00YTZmLTE5NmY1ZjI2NzBiNSIsImNvZ25pdG86Z3JvdXBzIjpbInVzLWVhc3QtMV9jNjN4TERiaHFfR29vZ2xlIl0sImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9jNjN4TERiaHEiLCJjb2duaXRvOnVzZXJuYW1lIjoiZ29vZ2xlXzEwNzE3ODQxMTU0OTMyMjM2MDc1NSIsImdpdmVuX25hbWUiOiJ4aWFvbmFuIiwibm9uY2UiOiJrb085U1RKcm04TnVBLVhiQmtXUjRIMzBlR2JZVWRqajN1UEVyVG9mbi1PaDdRYTl3NnlpSC1lTGN3d1czcnVELXM1T1ZUWTFjVHl5UnEtUVk3dFJvdGUyb3gzYkVXYXNfeDN6bjR2ZS1GcjJGZUN2aFk4ZFRSZVM2SnNzaTlMMGtSWWpUdWZhMWVOZnJvZllTeVVrRXc1V3ZUMENabnZ0dkpYcEFibGlFYjgiLCJhdWQiOiIxbWMyZnFyNmVobzkwYWswdGFqZXV2NTVncSIsImlkZW50aXRpZXMiOlt7ImRhdGVDcmVhdGVkIjoiMTcxNzU0MDc0Njc3MiIsInVzZXJJZCI6IjEwNzE3ODQxMTU0OTMyMjM2MDc1NSIsInByb3ZpZGVyTmFtZSI6Ikdvb2dsZSIsInByb3ZpZGVyVHlwZSI6Ikdvb2dsZSIsImlzc3VlciI6bnVsbCwicHJpbWFyeSI6InRydWUifV0sInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzE3NTUwNDk5LCJleHAiOjE3MTc2MzY4OTksImlhdCI6MTcxNzU1MDUwMCwiZmFtaWx5X25hbWUiOiJsaSIsImp0aSI6ImViMzM3ODg5LTc2NGYtNDY0NC1hMzhjLTZjNmZhODlmZTcyYiIsImVtYWlsIjoiYWxleC54aWFvbmFuQGdtYWlsLmNvbSJ9.mKxNVoQMjIla8gVgsp62EN-Fy2VaupmIYXHPv9Hfva0mvdVZ11KamJG0_gTGnk21nALBz8SPnmaFEFyCXqZRz-8XWkH54z-WzeT3-jeUo71e_JdKCNZYw8kYtfYZmL9KJUQrdi4iza-snaT7ofAZMsv3YXnVy1N-JVAa5sqIlOU8x_aAaaSw1AMVMPznD_C8GtdLFP7Bq_QMmUvCyfpnVdhF27L8mRp_YgdRlQETuRwUj-l1BXsOyAt-Hf0DC9sDAFnXh7lq1rs8XqnQt7TuqW04UHmsk1EMMrQ8OYqyQVEFb-qKabNCNwlTfeEm-Bp7sDQclbfyuNzZdSuRxnrv-Q'
AWS_REGION_NAME = 'us-east-1'


# AWS S3 Settings
AWS_S3_BUCKET_NAME = '5225-a3-images-demo'

# Django Storage Config
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

